name: Monthly Job

on:
  schedule:
    - cron: '0 0 5 * *'  # Fifth day of every month at midnight UTC
  workflow_dispatch:     # Allows manual run for testing

permissions:
  contents: write
  
jobs:
  run-monthly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Python script
        run: python main.py

      - name: Commit and push new files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/*.csv figures/*.png || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Added updated production data"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin HEAD:main
          fi

      - name: Read email summary
        id: email
        run: |
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          cat email_summary.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get latest monthly figure
        id: latest_figure
        run: |
          latest_file=$(ls -t figures/*monthly.png | head -n 1)
          echo "file=$latest_file" >> $GITHUB_OUTPUT

      - name: Send email with attachments
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: TEST PV Monthly Report - ${{ github.event.repository.name }}
          body: |
            Kære UEF medlemmer

            Find vedhæftet den seneste månedlige PV produktionsoversigt.

            ${{ steps.email.outputs.summary }}

            Med venlig hilsen
            UEF

          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          attachments: ${{ steps.latest_figure.outputs.file }}
