name: Monthly Report

on:
  schedule:
    - cron: '0 6 1 * *'  # At 06:00 UTC on the 1st of each month
  workflow_dispatch:     # (optional) manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

      name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome

    - name: Run script
      run: python main.py
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}