name: Monthly Job

on:
  schedule:
    - cron: '0 0 6 * *'  # Sixth day of every month at midnight UTC (to avoid it does not run at the same time as the quarterly job)
  workflow_dispatch:     # Allows manual run for testing

permissions:
  contents: write
  
jobs:
  run-monthly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Python script
        run: python monthly.py

      - name: Commit and push new files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/*.csv figures/*.png || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Added updated production data"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin HEAD:main
          fi

      - name: Read email summary
        id: email
        run: |
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          cat email_summary.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Get latest monthly figure
        id: latest_figure
        run: |
          latest_file=$(ls -t figures/*panel.png | head -n 1)
          echo "file=$latest_file" >> $GITHUB_OUTPUT

      - name: Send email with attachments
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Månedsoverblik - ${{ github.event.repository.name }}
          body: |
            Kære UEF medlemmer

            Her får I den samlede elproduktion fra vores fælles solcelleanlæg for den forgangne måned.

            Se vedhæftet figur for denne oversigt. 

            ${{ steps.email.outputs.summary }}

            Du kan selvfølgelig stadig følge med i produktionen ved at tilgå vores hjemmeside: https://www.uef.dk/installation-and-production

            Vi gør opmærksom på, at denne rapportering foregår automatisk, og der kan derfor forekomme afvigelser i forhold til de faktiske produktionsdata.

            Med solrige hilsener
            UEF

          to: ${{ secrets.EMAIL_TO_MONTHLY }}
          bcc: ${{ secrets.EMAIL_BCC_MONTHLY }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          attachments: ${{ steps.latest_figure.outputs.file }}
