name: Monthly Job

on:
  schedule:
    - cron: '0 0 1 * *'  # First day of every month at midnight UTC
  workflow_dispatch:     # Allows manual run for testing

jobs:
  run-monthly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Python script
        run: python main.py