name: Monthly Job

on:
  schedule:
    - cron: '0 0 1 * *'  # First day of every month at midnight UTC
  workflow_dispatch:     # Allows manual run for testing

permissions:
  contents: write
  
jobs:
  run-monthly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Python script
        run: python main.py

      - name: Commit and push new files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/*.csv
          git add figures/*.png
          git commit -m "Added new production data" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main